*/
  =====================================================
  DDL Script: Create Silver Tables
    =====================================================
Script Purpose:
This script creates tables in the 'silver' schema, dropping existing tables
  if they already exist.
    Run this script to re-define the DDL structure of bronze tables
  =========================================================
  */
  
IF OBJECT_ID ('silver.crm_cust_info', 'U' ) IS NOT NULL
DROP TABLE silver.crm_cust_info;
GO

CREATE TABLE silver.crm_cust_info(
	cst_id INT,
	cst_key NVARCHAR(50),
	cst_firstname NVARCHAR(50),
	cst_lastnaem NVARCHAR(50),
	cst_material_status NVARCHAR(50),
	cst_gndr NVARCHAR(50),
	cst_create_date DATE
);

CREATE TABLE silver.crm_prd_info(
prd_id INT,
prd_key NVARCHAR(50),
prd_nm NVARCHAR(50),
prd_cost INT,
prd_line NVARCHAR(50),
prd_start_dt DATETIME,
prd_end_dt DATETIME
);


DROP TABLE silver.crm_sales_details;
CREATE TABLE silver.crm_sales_details(
    sls_ord_num NVARCHAR(50),   -- SO43697
    sls_prd_key NVARCHAR(50),   -- BK-R93R-62
    sls_cust_id INT,            -- 21768
    sls_order_dt INT,           -- 20101229
    sls_ship_dt INT,            -- 20110105
    sls_due_dt INT,             -- 20110110
    sls_sales INT,              -- 3578
    sls_quantity INT,           -- 1
    sls_price INT               -- 3578
);

DROP TABLE silver.erp_loc_a101;
CREATE TABLE silver.erp_loc_a101 (
    cid NVARCHAR(50),
    cntry NVARCHAR(50)
);

CREATE TABLE silver.erp_cust_az12 (
	cid NVARCHAR(50),
	bdate DATE,
	gen NVARCHAR(50)
);

CREATE TABLE silver.erp_px_cat_g1v2 (
	id NVARCHAR(50),
	cat NVARCHAR(50),
	subcat NVARCHAR(50),
	maintenance NVARCHAR(50)
);
